import 'package:flutter/material.dart';

const primarybg = Color(0xFFFFFFFF);
const secondbg = Color(0xFF3D3DE9);
const cheryred = Color(0XFFef233c);
const secondtechbg = Color(0xFF6200ED);
const cardbg = Color(0xFFf4f7f6);
const bluebg = Color.fromRGBO(55, 48, 255, 1);
// const bluebg = Color(0XFF1A95B0);
const newbg = Color(0xFFF1F2F6);
const pclr = Color(0xFF56cfe1);
const white = Colors.white;
const limegreen = Color(0XFF70e000);
const black = Colors.black;
const greenbg = Color(0XFFEDF5EB);
const redbg = Color(0XFFFDEDEC);
const redfg = Color(0XFFE64639);
const yellowbg = Color(0XFFFFF7E6);
const yellowfg = Color(0XFFFFC444);
const vybg = Color(0XFFF2F4F8);
const limegreen2 = Color(0XFF9ef01a);
const nonactivebg = Color(0xFFf9f9f9);
const nonactivetxt = Color(0XFF989898);
const trans = Colors.transparent;
